name: Run unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.20
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Create database 
      run: |
        apt-get update
        apt-get install -y mysql-client
        mysql --host mysql -uroot -proot -e "CREATE DATABASE kreditplus"

    - name: Run migrations
      run: make migrateup

    - name: Test
      run: make test
